<?php
/**
 * Custom functions that act independently of the theme templates.
 *
 * Eventually, some of the functionality here could be replaced by core features.
 * 
 * @since 1.0.0
 * 
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package SmartyMagazine
 */

if (!function_exists('__smarty_magazine_body_classes')) {
	/**
	 * Adds custom classes to the array of body classes.
	 * 
	 * @since 1.0.0
	 * 
	 * @param array $classes Classes for the body element.
	 * 
	 * @return array Modified array of body classes.
	 * 
	 * @link https://developer.wordpress.org/reference/hooks/body_class/
	 */
	function __smarty_magazine_body_classes($classes) {
		// Adds a class of group-blog to blogs with more than 1 published author.
		if (is_multi_author()) {
			$classes[] = 'group-blog';
		}

		return $classes;
	}
	add_filter('body_class', '__smarty_magazine_body_classes');
}

if (!function_exists('__smarty_magazine_customizer_styles')) {
	/**
	 * Enqueue inline styles generated by customizer settings.
	 * 
	 * @since 1.0.0
	 *
	 * @return void
	 * 
	 * @link https://developer.wordpress.org/themes/basics/theme-functions/
	 */
	function __smarty_magazine_customizer_styles() {
		$font_size           = get_theme_mod('__smarty_magazine_font_size');

		$footer_bg_color     = get_theme_mod('__smarty_magazine_footer_bg_color', '#212529');
		$footer_text_color   = get_theme_mod('__smarty_magazine_footer_text_color', '#f9f9f9');
		$footer_hover_color  = get_theme_mod('__smarty_magazine_footer_text_hover_color', '#ffc107');

		$custom_css = '';
		
		if ($font_size) { $custom_css .= "body { font-size: {$font_size}px; }"; }
		if ($footer_bg_color) { $custom_css .= ".sm-footer { background: {$footer_bg_color}; }"; }
		if ($footer_text_color) { $custom_css .= ".sm-footer, .sm-footer p, .sm-footer a, .sm-footer-cont li a, .sm-footer-bar, .sm-footer-bar a { color: {$footer_text_color}; }"; }
		if ($footer_hover_color) { $custom_css .= ".sm-footer a:hover, .sm-footer-bar a:hover { color: {$footer_hover_color} !important; }"; }

		// Add Inline Styles
		wp_add_inline_style('sm-style', $custom_css);
	}
	add_action('wp_enqueue_scripts', '__smarty_magazine_customizer_styles');
}

/**
 * Disables the block editor from managing widgets.
 * 
 * @since 1.0.0
 */
add_filter('gutenberg_use_widgets_block_editor', '__return_false');
add_filter('use_widgets_block_editor', '__return_false');
