<?php

/**
 * Custom functions that act independently of the theme templates.
 *
 * Eventually, some of the functionality here could be replaced by core features.
 *
 * @package SmartyMagazine
 */

if (!function_exists('__smarty_magazine_body_classes')) {
	/**
	 * Adds custom classes to the array of body classes.
	 *
	 * @param array $classes Classes for the body element.
	 * @return array Modified array of body classes.
	 */
	function __smarty_magazine_body_classes($classes) {
		// Adds a class of group-blog to blogs with more than 1 published author.
		if (is_multi_author()) {
			$classes[] = 'group-blog';
		}

		return $classes;
	}
	add_filter('body_class', '__smarty_magazine_body_classes');
}

if (!function_exists('__smarty_magazine_customizer_styles')) {
	/**
	 * Enqueue inline styles generated by customizer settings.
	 *
	 * @return void
	 */
	function __smarty_magazine_customizer_styles() {
		$color 				= get_theme_mod('__smarty_magazine_font_color');
		$font_size 			= get_theme_mod('__smarty_magazine_font_size');
		$primary 			= get_theme_mod('__smarty_magazine_primary_color');
		$menu_bg 			= get_theme_mod('__smarty_magazine_menu_bg_color');
		$menu_color 		= get_theme_mod('__smarty_magazine_menu_color');
		$menu_hover_bg 		= get_theme_mod('__smarty_magazine_menu_hover_bg_color', '#be3434');
		$menu_color_hover 	= get_theme_mod('__smarty_magazine_menu_color_hover');
		$header_bg_color    = get_theme_mod('__smarty_magazine_header_bg_color', '#ffffff');
    	$header_text_color  = get_theme_mod('__smarty_magazine_header_text_color', '#000000');
		$footer_bg_color 	= get_theme_mod('__smarty_magazine_footer_bg_color', '#2f363e');
		$footer_text_color 	= get_theme_mod('__smarty_magazine_footer_text_color');
		$footer_hover_color = get_theme_mod('__smarty_magazine_footer_text_hover_color');

		$custom_css = '';

		// Apply Header Background Color
		if ($header_bg_color) {
			$custom_css .= "
			.sm-header {
				background-color: {$header_bg_color};
			}";
		}
	
		// Apply Header Text Logo Color
		if ($header_text_color) {
			$custom_css .= "
			.sm-logo > h1.site-title > a {
				color: {$header_text_color};
			}";
		}

		if ($color) {
			$custom_css .= "
			body, h1 a, h2 a, h3 a, h4 a, h5 a, h6 a,
			.sm-sidebar .sm-social-icons li .fa, a {
				color: {$color};
			}
			";
		}

		if ($font_size) {
			$custom_css .= "
			body {
				font-size: {$font_size}px;
			}
			";
		}

		if ($primary) {
			$custom_css .= "
			a:hover,
			.sm-footer-cont li a:hover,
			.sm-sec-menu li a:hover,
			.sm-featured-posts-wrap h2 a:hover,
			.sm-pagination-nav .current,
			.sm-footer .sm-news-layout-wrap a:hover {
				color: {$primary};
			}

			.sm-news-layout2 .sm-news-post:hover,
			.sm-pagination-nav .current,
			.sm-pagination-nav a:hover {
				border-color: {$primary};
			}

			.bt-news-ticker-tag:after {
				border-left-color: {$primary} !important;
			}

			.sticky {
				border-color: {$primary} !important;
			}

			.sm-news-layout1 .sm-news-post-img .fa:hover,
			.sm-news-layout-half .sm-news-post-img .fa:hover,
			.sm-sidebar-news .sm-news-post-img .fa:hover,
			.sm-footer h2:after,
			.sm-footer .tagcloud a:hover,
			.sm-related-posts .sm-news-post-img .fa:hover,
			.sm-search-bar,
			.bt-news-ticker-tag,
			.sm-category-posts .sm-news-post-img .fa:hover,
			.sm-category-post-readmore a:hover,
			.sm-nav-md-trigger:hover .fa,
			.tagcloud a:hover {
				background: {$primary};
			}
			";
		}

		$rgba = __smarty_magazine_hex2rgba($primary, 0.75);

		if ($rgba) {
			$custom_css .= "
			.sm-news-layout1 .sm-news-post-img .fa,
			.sm-news-layout-half .sm-news-post-img .fa,
			.sm-sidebar-news .sm-news-post-img .fa,
			.sm-related-posts .sm-news-post-img .fa,
			.sm-category-posts .sm-news-post-img .fa,
			#back-to-top:hover {
				background: {$rgba};
			}
			";
		}

		if ($menu_bg) {
			$custom_css .= "
			.sm-menu-bar,
			.sm-main-menu li ul {
				background: {$menu_bg};
			}
			";
		}

		if ($menu_color) {
			$custom_css .= "
			.sm-main-menu li a,
			.sm-main-menu li:hover,
			.menu-item-has-children:after,
			.current-menu-item a,
			.sm-nav-md li a,
			.sm-nav-md .menu-item-has-children:after,
			.sm-logo-md a,
			.sm-nav-md-trigger {
				color: {$menu_color};
			}
			";
		}

		if ($menu_hover_bg) {
			$custom_css .= "
			.sm-main-menu li:hover,
			.sm-main-menu li a:hover,
			.sm-main-menu li.current-menu-item > a,
			.sm-nav-md li a:hover,
			.current-menu-item.menu-item-has-children {
				background: {$menu_hover_bg};
				color: #fff;
			}
			";
		}

		if ($menu_color_hover) {
			$custom_css .= "
			.sm-main-menu li:hover,
			.sm-main-menu li a:hover,
			.sm-main-menu li .current-menu-item > a,
			.sm-nav-md li a:hover,
			.current-menu-item.menu-item-has-children:after,
			.current-menu-item.menu-item-has-children:hover:after,
			.menu-item-has-children:hover:after,
			.sm-main-menu li:hover > a {
				color: {$menu_color_hover};
			}
			";
		}

		$sm_related_posts = 33.333333;
		$custom_css .= ".sm-related-posts li { width: calc({$sm_related_posts}% - 20px); }";
		$custom_css .= ".sm-footer { background: {$footer_bg_color}; }";

		if ($footer_text_color) {
			$custom_css .= ".sm-footer, .sm-footer p, .sm-footer a, .sm-footer-cont li a, .sm-footer-bar, .sm-footer-bar a { color: {$footer_text_color}; }";
		}

		if ($footer_hover_color) {
			$custom_css .= ".sm-footer a:hover, .sm-footer-bar a:hover { color: {$footer_hover_color} !important; }";
		}

		wp_add_inline_style('sm-style', $custom_css);
	}
	add_action('wp_enqueue_scripts', '__smarty_magazine_customizer_styles');
}

/**
 * Disables the block editor from managing widgets.
 */
add_filter('gutenberg_use_widgets_block_editor', '__return_false');
add_filter('use_widgets_block_editor', '__return_false');
